"""added request table

Revision ID: 32215d4b8aba
Revises: 9631438e4b30
Create Date: 2024-11-14 01:22:08.828722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32215d4b8aba'
down_revision: Union[str, None] = '9631438e4b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('company_id', sa.UUID(), nullable=False), schema='colauncha_web')
    op.create_foreign_key(None, 'requests', 'company', ['company_id'], ['id'], source_schema='colauncha_web', referent_schema='colauncha_web', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', schema='colauncha_web', type_='foreignkey')
    op.drop_column('requests', 'company_id', schema='colauncha_web')
    # ### end Alembic commands ###
