"""added request table

Revision ID: 5317baa76837
Revises: 32215d4b8aba
Create Date: 2024-11-14 01:49:08.293669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5317baa76837'
down_revision: Union[str, None] = '32215d4b8aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('required_skills', sa.JSON(), nullable=True), schema='colauncha_web')
    op.drop_column('requests', 'skills_required', schema='colauncha_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('skills_required', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='colauncha_web')
    op.drop_column('requests', 'required_skills', schema='colauncha_web')
    # ### end Alembic commands ###
