"""made email a unique key in company table

Revision ID: 9631438e4b30
Revises: d8d2dcd7f996
Create Date: 2024-11-13 18:13:55.289412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9631438e4b30'
down_revision: Union[str, None] = 'd8d2dcd7f996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['name'], schema='colauncha_web')
    op.create_unique_constraint(None, 'company', ['email'], schema='colauncha_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', schema='colauncha_web', type_='unique')
    op.drop_constraint(None, 'company', schema='colauncha_web', type_='unique')
    # ### end Alembic commands ###
